### ISSUE TITLE
微服务会加大时间开销，这与IM追求实时性有冲突吧？

### ISSUE THREAD

**Issue by henrylee2cn** [oikomi/FishChatServer2#1]
微服务会加长时间的开销，这与IM追求实时性有冲突吧？另外grpc提高了接口对接的规范性，但是同样是拉慢了响应速度。

**Comment by oikomi** [comment]
如果理论上讲确实有开销，但是相对于C端的开销，这部分还是很微小的。另外服务端设计更多的考虑到了服务的可理解型、易读性以及增删业务的简单性，从这个角度来讲一点点的牺牲还是值得的。
